/********************************************************************
**       This java file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/


package com.game.metaxml;

import java.util.ArrayList;

public final class Cspb {
 	private Cspb(){}
	/** dir req */
	public static short  MSG__TYPE__DIR_REQ  = 1;
	/** dir res */
	public static short  MSG__TYPE__DIR_RES  = 2;
	/** 认证请求 */
	public static short  MSG__TYPE__AUTH_REQ  = 3;
	/** 认证回复 */
	public static short  MSG__TYPE__AUTH_RES  = 4;
	/**  登陆 请求 */
	public static short  MSG__TYPE__LOGIN_REQ  = 5;
	/** 登陆 回复 */
	public static short  MSG__TYPE__LOGIN_RES  = 6;
	/** 心跳包请求 */
	public static short  MSG__TYPE__HEART_REQ  = 9;
	/** 心跳包回复 */
	public static short  MSG__TYPE__HEART_RES  = 10;
	/** RegTaskReq 注册7日活动 */
	public static short  MSG__TYPE__REG_TASK_REQ  = 95;
	/** RegTaskReq 注册7日活动回复  rsp 是活动 */
	public static short  MSG__TYPE__REG_TASK_RSP  = 96;

}