/********************************************************************
**       This java file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/


package com.game.metaxml;

import java.util.ArrayList;

public final class ProtoComm {
 	private ProtoComm(){}
	/** 探索任务区域停留时间单位秒 */
	public static int  TAKS_AREA_STOP_TIME  = 3;
	/** 商品购买面板,32位一位表示一个面板 */
	public static enum SHOPPING_BUY_UI_TYPE {
		/**默认在商城面板购买商品*/
		SHOPPING_BUY_UI_SHANGCHENG,
		/**背包快捷购买*/
		SHOPPING_BUY_UI_PACKAGE,
		/**复活快捷购买*/
		SHOPPING_BUY_UI_RELIVE,

	}
	/** 就和爽肤水 */
	public final static class BoonAddEvent  implements java.io.Serializable {
 		public BoonAddEvent(){}
		/** 取值为BOON_ADD_TYPE */
		private  int  ID = 88;
		/** 加成百分比 */
		private  String  Per = "hello word";
		/** 时间 */
		private  int  time;
		/** 标题 */
		private  short  title = 5;
		public int getID(){
			return this.ID;
		}
		public void setID(int ID){
			this.ID = ID;
		}
		public String getPer(){
			return this.Per;
		}
		public void setPer(String Per){
			this.Per = Per;
		}
		public int getTime(){
			return this.time;
		}
		public void setTime(int time){
			this.time = time;
		}
		public short getTitle(){
			return this.title;
		}
		public void setTitle(short title){
			this.title = title;
		}

	}
	public final static class JjcOne  implements java.io.Serializable {
 		public JjcOne(){}
		private  int  iDirty;
		private  int  iTimeCount;
		public int getIDirty(){
			return this.iDirty;
		}
		public void setIDirty(int iDirty){
			this.iDirty = iDirty;
		}
		public int getITimeCount(){
			return this.iTimeCount;
		}
		public void setITimeCount(int iTimeCount){
			this.iTimeCount = iTimeCount;
		}

	}
	public final static class JjcAuth  implements java.io.Serializable {
 		public JjcAuth(){}
		private  int  iStat;
		private  int  iDBCount;
		private  int  iNum;
		private  ArrayList<JjcOne>  JjcOne;
		public int getIStat(){
			return this.iStat;
		}
		public void setIStat(int iStat){
			this.iStat = iStat;
		}
		public int getIDBCount(){
			return this.iDBCount;
		}
		public void setIDBCount(int iDBCount){
			this.iDBCount = iDBCount;
		}
		public int getINum(){
			return this.iNum;
		}
		public void setINum(int iNum){
			this.iNum = iNum;
		}
		public ArrayList<JjcOne> getJjcOne(){
			return this.JjcOne;
		}
		public void setJjcOne(ArrayList<JjcOne> JjcOne){
			this.JjcOne = JjcOne;
		}

	}
	/** 最大卡牌数 */
	public static int  MAX_CARD_NUM  = 218;
	/** 最大装备数 */
	public static int  MAX_ARM_NUM  = 100;
	@javax.xml.bind.annotation.XmlRootElement
	public final static class RoleData  implements java.io.Serializable {
 		public RoleData(){}
		private  int  Uin;
		/** global unique role id */
		private  int  RoleID;
		private  String  RoleName;
		private  int  Lvl;
		private  int  IconID;
		private  int  CreateTime;
		private  int  LastLogin;
		private  int  LastLogout;
		private  int  Money;
		private  int  Gold;
		private  int  RMB;
		private  int  Tili;
		private  int  MaxTili;
		private  int  Exp;
		private  int  WorldID;
		private  int  SectionID;
		@com.game.annotation.BinaryDb
		private  RoleMisc  Misc;
		public int getUin(){
			return this.Uin;
		}
		public void setUin(int Uin){
			this.Uin = Uin;
		}
		public int getRoleID(){
			return this.RoleID;
		}
		public void setRoleID(int RoleID){
			this.RoleID = RoleID;
		}
		public String getRoleName(){
			return this.RoleName;
		}
		public void setRoleName(String RoleName){
			this.RoleName = RoleName;
		}
		public int getLvl(){
			return this.Lvl;
		}
		public void setLvl(int Lvl){
			this.Lvl = Lvl;
		}
		public int getIconID(){
			return this.IconID;
		}
		public void setIconID(int IconID){
			this.IconID = IconID;
		}
		public int getCreateTime(){
			return this.CreateTime;
		}
		public void setCreateTime(int CreateTime){
			this.CreateTime = CreateTime;
		}
		public int getLastLogin(){
			return this.LastLogin;
		}
		public void setLastLogin(int LastLogin){
			this.LastLogin = LastLogin;
		}
		public int getLastLogout(){
			return this.LastLogout;
		}
		public void setLastLogout(int LastLogout){
			this.LastLogout = LastLogout;
		}
		public int getMoney(){
			return this.Money;
		}
		public void setMoney(int Money){
			this.Money = Money;
		}
		public int getGold(){
			return this.Gold;
		}
		public void setGold(int Gold){
			this.Gold = Gold;
		}
		public int getRMB(){
			return this.RMB;
		}
		public void setRMB(int RMB){
			this.RMB = RMB;
		}
		public int getTili(){
			return this.Tili;
		}
		public void setTili(int Tili){
			this.Tili = Tili;
		}
		public int getMaxTili(){
			return this.MaxTili;
		}
		public void setMaxTili(int MaxTili){
			this.MaxTili = MaxTili;
		}
		public int getExp(){
			return this.Exp;
		}
		public void setExp(int Exp){
			this.Exp = Exp;
		}
		public int getWorldID(){
			return this.WorldID;
		}
		public void setWorldID(int WorldID){
			this.WorldID = WorldID;
		}
		public int getSectionID(){
			return this.SectionID;
		}
		public void setSectionID(int SectionID){
			this.SectionID = SectionID;
		}
		public RoleMisc getMisc(){
			return this.Misc;
		}
		public void setMisc(RoleMisc Misc){
			this.Misc = Misc;
		}

	}
	public final static class RoleMisc  implements java.io.Serializable {
 		public RoleMisc(){}
		/**  */
		private  int  lastupdate;
		private  int  Seq;
		/** 战姬情报 */
		private  int  ZhanjiQB;
		/** 兵器图纸 */
		private  int  BingqiTz;
		/** 快速搜索 */
		private  int  QSearch;
		/** 快速治疗 */
		private  int  QCure;
		private  int  XlReel;
		private  int  XlReelG;
		private  ArmInfo  ArmInfo =  new ArmInfo();
		public int getLastupdate(){
			return this.lastupdate;
		}
		public void setLastupdate(int lastupdate){
			this.lastupdate = lastupdate;
		}
		public int getSeq(){
			return this.Seq;
		}
		public void setSeq(int Seq){
			this.Seq = Seq;
		}
		public int getZhanjiQB(){
			return this.ZhanjiQB;
		}
		public void setZhanjiQB(int ZhanjiQB){
			this.ZhanjiQB = ZhanjiQB;
		}
		public int getBingqiTz(){
			return this.BingqiTz;
		}
		public void setBingqiTz(int BingqiTz){
			this.BingqiTz = BingqiTz;
		}
		public int getQSearch(){
			return this.QSearch;
		}
		public void setQSearch(int QSearch){
			this.QSearch = QSearch;
		}
		public int getQCure(){
			return this.QCure;
		}
		public void setQCure(int QCure){
			this.QCure = QCure;
		}
		public int getXlReel(){
			return this.XlReel;
		}
		public void setXlReel(int XlReel){
			this.XlReel = XlReel;
		}
		public int getXlReelG(){
			return this.XlReelG;
		}
		public void setXlReelG(int XlReelG){
			this.XlReelG = XlReelG;
		}
		public ArmInfo getArmInfo(){
			return this.ArmInfo;
		}
		public void setArmInfo(ArmInfo ArmInfo){
			this.ArmInfo = ArmInfo;
		}

	}
	public final static class ArmInfo  implements java.io.Serializable {
 		public ArmInfo(){}
		private  int  MaxNum;
		private  int  Num;
		private  ArrayList<ArmOne>  One;
		public int getMaxNum(){
			return this.MaxNum;
		}
		public void setMaxNum(int MaxNum){
			this.MaxNum = MaxNum;
		}
		public int getNum(){
			return this.Num;
		}
		public void setNum(int Num){
			this.Num = Num;
		}
		public ArrayList<ArmOne> getOne(){
			return this.One;
		}
		public void setOne(ArrayList<ArmOne> One){
			this.One = One;
		}

	}
	public final static class ArmOne  implements java.io.Serializable {
 		public ArmOne(){}
		private  int  ID;
		private  int  Source;
		private  int  WID;
		/** 强化等级 */
		private  int  StrLvl;
		/** 装备等级 */
		private  int  Star;
		public int getID(){
			return this.ID;
		}
		public void setID(int ID){
			this.ID = ID;
		}
		public int getSource(){
			return this.Source;
		}
		public void setSource(int Source){
			this.Source = Source;
		}
		public int getWID(){
			return this.WID;
		}
		public void setWID(int WID){
			this.WID = WID;
		}
		public int getStrLvl(){
			return this.StrLvl;
		}
		public void setStrLvl(int StrLvl){
			this.StrLvl = StrLvl;
		}
		public int getStar(){
			return this.Star;
		}
		public void setStar(int Star){
			this.Star = Star;
		}

	}
	/** player 类 */
	public final static class Player  implements java.io.Serializable {
 		public Player(){}
		/**  */
		private  int  iMagic;
		/**  */
		private  long  tActive;
		/**  */
		private  char  eStatus;
		/**  */
		private  String  szAccount = "test - account";
		/**  */
		private  String  aMacAdd;
		/**  */
		private  int  iUinCachePos;
		/**  */
		private  String  sRes1;
		/**  */
		private  int  iIdx;
		/**  */
		private  RoleData  stRoleData;
		/**  */
		private  String  sRes2;
		/**  */
		private  ConnectInfo  stConnectInfo;
		public int getIMagic(){
			return this.iMagic;
		}
		public void setIMagic(int iMagic){
			this.iMagic = iMagic;
		}
		public long getTActive(){
			return this.tActive;
		}
		public void setTActive(long tActive){
			this.tActive = tActive;
		}
		public char getEStatus(){
			return this.eStatus;
		}
		public void setEStatus(char eStatus){
			this.eStatus = eStatus;
		}
		public String getSzAccount(){
			return this.szAccount;
		}
		public void setSzAccount(String szAccount){
			this.szAccount = szAccount;
		}
		public String getAMacAdd(){
			return this.aMacAdd;
		}
		public void setAMacAdd(String aMacAdd){
			this.aMacAdd = aMacAdd;
		}
		public int getIUinCachePos(){
			return this.iUinCachePos;
		}
		public void setIUinCachePos(int iUinCachePos){
			this.iUinCachePos = iUinCachePos;
		}
		public String getSRes1(){
			return this.sRes1;
		}
		public void setSRes1(String sRes1){
			this.sRes1 = sRes1;
		}
		public int getIIdx(){
			return this.iIdx;
		}
		public void setIIdx(int iIdx){
			this.iIdx = iIdx;
		}
		public RoleData getStRoleData(){
			return this.stRoleData;
		}
		public void setStRoleData(RoleData stRoleData){
			this.stRoleData = stRoleData;
		}
		public String getSRes2(){
			return this.sRes2;
		}
		public void setSRes2(String sRes2){
			this.sRes2 = sRes2;
		}
		public ConnectInfo getStConnectInfo(){
			return this.stConnectInfo;
		}
		public void setStConnectInfo(ConnectInfo stConnectInfo){
			this.stConnectInfo = stConnectInfo;
		}

	}
	/** 连接信息 */
	public final static class ConnectInfo  implements java.io.Serializable {
 		public ConnectInfo(){}
		/**  */
		private  char  chVer;
		/**  */
		private  char  chCmd;
		/**  */
		private  char  chExtraType;
		/**  */
		private  char  chTimeStampType;
		public char getChVer(){
			return this.chVer;
		}
		public void setChVer(char chVer){
			this.chVer = chVer;
		}
		public char getChCmd(){
			return this.chCmd;
		}
		public void setChCmd(char chCmd){
			this.chCmd = chCmd;
		}
		public char getChExtraType(){
			return this.chExtraType;
		}
		public void setChExtraType(char chExtraType){
			this.chExtraType = chExtraType;
		}
		public char getChTimeStampType(){
			return this.chTimeStampType;
		}
		public void setChTimeStampType(char chTimeStampType){
			this.chTimeStampType = chTimeStampType;
		}

	}
	/** 服务器配置 */
	public final static class SvrConfig  implements java.io.Serializable {
 		public SvrConfig(){}
		/** ip 地址 */
		private  String  IP;
		/** 端口号 */
		private  int  Port;
		/** 服务名称 */
		private  String  SvrName;
		public String getIP(){
			return this.IP;
		}
		public void setIP(String IP){
			this.IP = IP;
		}
		public int getPort(){
			return this.Port;
		}
		public void setPort(int Port){
			this.Port = Port;
		}
		public String getSvrName(){
			return this.SvrName;
		}
		public void setSvrName(String SvrName){
			this.SvrName = SvrName;
		}

	}
	/** 用户认证 */
	public final static class Account  implements java.io.Serializable {
 		public Account(){}
		/** uin */
		private  int  Uin;
		/** uin */
		private  String  RoleName;
		/** uin */
		private  String  Password;
		public int getUin(){
			return this.Uin;
		}
		public void setUin(int Uin){
			this.Uin = Uin;
		}
		public String getRoleName(){
			return this.RoleName;
		}
		public void setRoleName(String RoleName){
			this.RoleName = RoleName;
		}
		public String getPassword(){
			return this.Password;
		}
		public void setPassword(String Password){
			this.Password = Password;
		}

	}
	/** 装备  该类可以和 xml 互转  */
	@javax.xml.bind.annotation.XmlRootElement
	public final static class Armdef  implements java.io.Serializable {
 		public Armdef(){}
		private  int  ID;
		private  String  name;
		private  ArrayList<RlMoneyInfo>  RlMoney;
		private  RecastMoneyInfo  RecastMoney;
		public int getID(){
			return this.ID;
		}
		public void setID(int ID){
			this.ID = ID;
		}
		public String getName(){
			return this.name;
		}
		public void setName(String name){
			this.name = name;
		}
		public ArrayList<RlMoneyInfo> getRlMoney(){
			return this.RlMoney;
		}
		public void setRlMoney(ArrayList<RlMoneyInfo> RlMoney){
			this.RlMoney = RlMoney;
		}
		public RecastMoneyInfo getRecastMoney(){
			return this.RecastMoney;
		}
		public void setRecastMoney(RecastMoneyInfo RecastMoney){
			this.RecastMoney = RecastMoney;
		}

	}
	public final static class RecastMoneyInfo  implements java.io.Serializable {
 		public RecastMoneyInfo(){}
		private  int  Num;
		private  int  Type;
		public int getNum(){
			return this.Num;
		}
		public void setNum(int Num){
			this.Num = Num;
		}
		public int getType(){
			return this.Type;
		}
		public void setType(int Type){
			this.Type = Type;
		}

	}
	public final static class RlMoneyInfo  implements java.io.Serializable {
 		public RlMoneyInfo(){}
		private  int  Num;
		private  int  Type;
		public int getNum(){
			return this.Num;
		}
		public void setNum(int Num){
			this.Num = Num;
		}
		public int getType(){
			return this.Type;
		}
		public void setType(int Type){
			this.Type = Type;
		}

	}

}