/********************************************************************
**       This java file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/


package com.game.metaxml;

import java.util.ArrayList;

public final class ResdbMeta {
 	private ResdbMeta(){}
	public final static class CardDef  implements java.io.Serializable {
 		public CardDef(){}
		private  int  ID;
		private  int  Type;
		private  int  Star;
		private  int  Hp;
		private  int  Wuli;
		private  int  Wuxiu;
		private  int  Zhili;
		private  int  Zhixiu;
		private  int  Fangyu;
		private  int  Fangxiu;
		private  int  Zhencha;
		private  int  Zhan;
		private  int  Zhuibei;
		private  int  Xinyun;
		private  int  Mingzhong;
		private  int  Shanbi;
		private  int  NextStarID;
		/** 关卡消耗体力 */
		private  int  Tili;
		private  ArrayList<CardSkill>  Skills;
		private  int  SearchTime;
		private  int  StarUpLvl;
		private  int  StarUpGold;
		private  int  StarUpShuijing;
		private  int  StarUpCardNum;
		private  int  StarUpCardID;
		private  int  WuliLvlLimit;
		private  int  ZhiliLvlLimit;
		private  int  FangyuLvlLimit;
		private  int  WuliExp;
		private  int  ZhiliExp;
		private  int  FangyuExp;
		private  int  GroupID;
		private  int  HpXiu;
		private  int  ZhenchaXiu;
		private  int  ZhanXiu;
		private  int  ZhuibeiXiu;
		private  int  XinyunXiu;
		private  String  Name;
		private  int  MaxLvl;
		private  int  Exp;
		/** 暴击伤害 除以1000 */
		private  int  BaojiShangHai;
		/** 冲锋战出售速度 */
		private  int  CfSpeed;
		/** 追击战出售速度 */
		private  int  ZjSpeed;
		private  CardActivation  Active;
		private  int  BeAttkWeight;
		private  int  Pingji;
		private  int  Career;
		private  int  CardScore;
		private  int  EvolveUpGradeMinlvl;
		private  int  EvolveMinActiveCount;
		private  int  EvolveUpgradeCostID;
		private  int  EvolveUpgradeCostValue;
		private  int  EvolveCardId;
		public int getID(){
			return this.ID;
		}
		public void setID(int ID){
			this.ID = ID;
		}
		public int getType(){
			return this.Type;
		}
		public void setType(int Type){
			this.Type = Type;
		}
		public int getStar(){
			return this.Star;
		}
		public void setStar(int Star){
			this.Star = Star;
		}
		public int getHp(){
			return this.Hp;
		}
		public void setHp(int Hp){
			this.Hp = Hp;
		}
		public int getWuli(){
			return this.Wuli;
		}
		public void setWuli(int Wuli){
			this.Wuli = Wuli;
		}
		public int getWuxiu(){
			return this.Wuxiu;
		}
		public void setWuxiu(int Wuxiu){
			this.Wuxiu = Wuxiu;
		}
		public int getZhili(){
			return this.Zhili;
		}
		public void setZhili(int Zhili){
			this.Zhili = Zhili;
		}
		public int getZhixiu(){
			return this.Zhixiu;
		}
		public void setZhixiu(int Zhixiu){
			this.Zhixiu = Zhixiu;
		}
		public int getFangyu(){
			return this.Fangyu;
		}
		public void setFangyu(int Fangyu){
			this.Fangyu = Fangyu;
		}
		public int getFangxiu(){
			return this.Fangxiu;
		}
		public void setFangxiu(int Fangxiu){
			this.Fangxiu = Fangxiu;
		}
		public int getZhencha(){
			return this.Zhencha;
		}
		public void setZhencha(int Zhencha){
			this.Zhencha = Zhencha;
		}
		public int getZhan(){
			return this.Zhan;
		}
		public void setZhan(int Zhan){
			this.Zhan = Zhan;
		}
		public int getZhuibei(){
			return this.Zhuibei;
		}
		public void setZhuibei(int Zhuibei){
			this.Zhuibei = Zhuibei;
		}
		public int getXinyun(){
			return this.Xinyun;
		}
		public void setXinyun(int Xinyun){
			this.Xinyun = Xinyun;
		}
		public int getMingzhong(){
			return this.Mingzhong;
		}
		public void setMingzhong(int Mingzhong){
			this.Mingzhong = Mingzhong;
		}
		public int getShanbi(){
			return this.Shanbi;
		}
		public void setShanbi(int Shanbi){
			this.Shanbi = Shanbi;
		}
		public int getNextStarID(){
			return this.NextStarID;
		}
		public void setNextStarID(int NextStarID){
			this.NextStarID = NextStarID;
		}
		public int getTili(){
			return this.Tili;
		}
		public void setTili(int Tili){
			this.Tili = Tili;
		}
		public ArrayList<CardSkill> getSkills(){
			return this.Skills;
		}
		public void setSkills(ArrayList<CardSkill> Skills){
			this.Skills = Skills;
		}
		public int getSearchTime(){
			return this.SearchTime;
		}
		public void setSearchTime(int SearchTime){
			this.SearchTime = SearchTime;
		}
		public int getStarUpLvl(){
			return this.StarUpLvl;
		}
		public void setStarUpLvl(int StarUpLvl){
			this.StarUpLvl = StarUpLvl;
		}
		public int getStarUpGold(){
			return this.StarUpGold;
		}
		public void setStarUpGold(int StarUpGold){
			this.StarUpGold = StarUpGold;
		}
		public int getStarUpShuijing(){
			return this.StarUpShuijing;
		}
		public void setStarUpShuijing(int StarUpShuijing){
			this.StarUpShuijing = StarUpShuijing;
		}
		public int getStarUpCardNum(){
			return this.StarUpCardNum;
		}
		public void setStarUpCardNum(int StarUpCardNum){
			this.StarUpCardNum = StarUpCardNum;
		}
		public int getStarUpCardID(){
			return this.StarUpCardID;
		}
		public void setStarUpCardID(int StarUpCardID){
			this.StarUpCardID = StarUpCardID;
		}
		public int getWuliLvlLimit(){
			return this.WuliLvlLimit;
		}
		public void setWuliLvlLimit(int WuliLvlLimit){
			this.WuliLvlLimit = WuliLvlLimit;
		}
		public int getZhiliLvlLimit(){
			return this.ZhiliLvlLimit;
		}
		public void setZhiliLvlLimit(int ZhiliLvlLimit){
			this.ZhiliLvlLimit = ZhiliLvlLimit;
		}
		public int getFangyuLvlLimit(){
			return this.FangyuLvlLimit;
		}
		public void setFangyuLvlLimit(int FangyuLvlLimit){
			this.FangyuLvlLimit = FangyuLvlLimit;
		}
		public int getWuliExp(){
			return this.WuliExp;
		}
		public void setWuliExp(int WuliExp){
			this.WuliExp = WuliExp;
		}
		public int getZhiliExp(){
			return this.ZhiliExp;
		}
		public void setZhiliExp(int ZhiliExp){
			this.ZhiliExp = ZhiliExp;
		}
		public int getFangyuExp(){
			return this.FangyuExp;
		}
		public void setFangyuExp(int FangyuExp){
			this.FangyuExp = FangyuExp;
		}
		public int getGroupID(){
			return this.GroupID;
		}
		public void setGroupID(int GroupID){
			this.GroupID = GroupID;
		}
		public int getHpXiu(){
			return this.HpXiu;
		}
		public void setHpXiu(int HpXiu){
			this.HpXiu = HpXiu;
		}
		public int getZhenchaXiu(){
			return this.ZhenchaXiu;
		}
		public void setZhenchaXiu(int ZhenchaXiu){
			this.ZhenchaXiu = ZhenchaXiu;
		}
		public int getZhanXiu(){
			return this.ZhanXiu;
		}
		public void setZhanXiu(int ZhanXiu){
			this.ZhanXiu = ZhanXiu;
		}
		public int getZhuibeiXiu(){
			return this.ZhuibeiXiu;
		}
		public void setZhuibeiXiu(int ZhuibeiXiu){
			this.ZhuibeiXiu = ZhuibeiXiu;
		}
		public int getXinyunXiu(){
			return this.XinyunXiu;
		}
		public void setXinyunXiu(int XinyunXiu){
			this.XinyunXiu = XinyunXiu;
		}
		public String getName(){
			return this.Name;
		}
		public void setName(String Name){
			this.Name = Name;
		}
		public int getMaxLvl(){
			return this.MaxLvl;
		}
		public void setMaxLvl(int MaxLvl){
			this.MaxLvl = MaxLvl;
		}
		public int getExp(){
			return this.Exp;
		}
		public void setExp(int Exp){
			this.Exp = Exp;
		}
		public int getBaojiShangHai(){
			return this.BaojiShangHai;
		}
		public void setBaojiShangHai(int BaojiShangHai){
			this.BaojiShangHai = BaojiShangHai;
		}
		public int getCfSpeed(){
			return this.CfSpeed;
		}
		public void setCfSpeed(int CfSpeed){
			this.CfSpeed = CfSpeed;
		}
		public int getZjSpeed(){
			return this.ZjSpeed;
		}
		public void setZjSpeed(int ZjSpeed){
			this.ZjSpeed = ZjSpeed;
		}
		public CardActivation getActive(){
			return this.Active;
		}
		public void setActive(CardActivation Active){
			this.Active = Active;
		}
		public int getBeAttkWeight(){
			return this.BeAttkWeight;
		}
		public void setBeAttkWeight(int BeAttkWeight){
			this.BeAttkWeight = BeAttkWeight;
		}
		public int getPingji(){
			return this.Pingji;
		}
		public void setPingji(int Pingji){
			this.Pingji = Pingji;
		}
		public int getCareer(){
			return this.Career;
		}
		public void setCareer(int Career){
			this.Career = Career;
		}
		public int getCardScore(){
			return this.CardScore;
		}
		public void setCardScore(int CardScore){
			this.CardScore = CardScore;
		}
		public int getEvolveUpGradeMinlvl(){
			return this.EvolveUpGradeMinlvl;
		}
		public void setEvolveUpGradeMinlvl(int EvolveUpGradeMinlvl){
			this.EvolveUpGradeMinlvl = EvolveUpGradeMinlvl;
		}
		public int getEvolveMinActiveCount(){
			return this.EvolveMinActiveCount;
		}
		public void setEvolveMinActiveCount(int EvolveMinActiveCount){
			this.EvolveMinActiveCount = EvolveMinActiveCount;
		}
		public int getEvolveUpgradeCostID(){
			return this.EvolveUpgradeCostID;
		}
		public void setEvolveUpgradeCostID(int EvolveUpgradeCostID){
			this.EvolveUpgradeCostID = EvolveUpgradeCostID;
		}
		public int getEvolveUpgradeCostValue(){
			return this.EvolveUpgradeCostValue;
		}
		public void setEvolveUpgradeCostValue(int EvolveUpgradeCostValue){
			this.EvolveUpgradeCostValue = EvolveUpgradeCostValue;
		}
		public int getEvolveCardId(){
			return this.EvolveCardId;
		}
		public void setEvolveCardId(int EvolveCardId){
			this.EvolveCardId = EvolveCardId;
		}

	}
	public final static class CardSkill  implements java.io.Serializable {
 		public CardSkill(){}
		private  int  ID;
		private  int  Lvl;
		public int getID(){
			return this.ID;
		}
		public void setID(int ID){
			this.ID = ID;
		}
		public int getLvl(){
			return this.Lvl;
		}
		public void setLvl(int Lvl){
			this.Lvl = Lvl;
		}

	}
	public final static class CardActivation  implements java.io.Serializable {
 		public CardActivation(){}
		private  int  ActiveID;
		private  ArrayList<CardActiveOne>  One;
		public int getActiveID(){
			return this.ActiveID;
		}
		public void setActiveID(int ActiveID){
			this.ActiveID = ActiveID;
		}
		public ArrayList<CardActiveOne> getOne(){
			return this.One;
		}
		public void setOne(ArrayList<CardActiveOne> One){
			this.One = One;
		}

	}
	public final static class CardActiveOne  implements java.io.Serializable {
 		public CardActiveOne(){}
		private  int  ID;
		private  int  Lvl;
		private  int  Use;
		private  int  AddAttrID;
		private  int  AddAttrVal;
		public int getID(){
			return this.ID;
		}
		public void setID(int ID){
			this.ID = ID;
		}
		public int getLvl(){
			return this.Lvl;
		}
		public void setLvl(int Lvl){
			this.Lvl = Lvl;
		}
		public int getUse(){
			return this.Use;
		}
		public void setUse(int Use){
			this.Use = Use;
		}
		public int getAddAttrID(){
			return this.AddAttrID;
		}
		public void setAddAttrID(int AddAttrID){
			this.AddAttrID = AddAttrID;
		}
		public int getAddAttrVal(){
			return this.AddAttrVal;
		}
		public void setAddAttrVal(int AddAttrVal){
			this.AddAttrVal = AddAttrVal;
		}

	}

}