// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Misc.proto

public final class MiscBean {
  private MiscBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TaskInfoOneOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 WeekNum = 1;
    /**
     * <code>required int32 WeekNum = 1;</code>
     */
    boolean hasWeekNum();
    /**
     * <code>required int32 WeekNum = 1;</code>
     */
    int getWeekNum();

    // required int32 Num = 2;
    /**
     * <code>required int32 Num = 2;</code>
     */
    boolean hasNum();
    /**
     * <code>required int32 Num = 2;</code>
     */
    int getNum();

    // required int32 Flag = 3;
    /**
     * <code>required int32 Flag = 3;</code>
     */
    boolean hasFlag();
    /**
     * <code>required int32 Flag = 3;</code>
     */
    int getFlag();

    // required int32 Stat = 4;
    /**
     * <code>required int32 Stat = 4;</code>
     */
    boolean hasStat();
    /**
     * <code>required int32 Stat = 4;</code>
     */
    int getStat();

    // required int32 ID = 5;
    /**
     * <code>required int32 ID = 5;</code>
     */
    boolean hasID();
    /**
     * <code>required int32 ID = 5;</code>
     */
    int getID();

    // required int32 DayNum = 6;
    /**
     * <code>required int32 DayNum = 6;</code>
     */
    boolean hasDayNum();
    /**
     * <code>required int32 DayNum = 6;</code>
     */
    int getDayNum();
  }
  /**
   * Protobuf type {@code TaskInfoOne}
   */
  public static final class TaskInfoOne extends
      com.google.protobuf.GeneratedMessage
      implements TaskInfoOneOrBuilder {
    // Use TaskInfoOne.newBuilder() to construct.
    private TaskInfoOne(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaskInfoOne(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaskInfoOne defaultInstance;
    public static TaskInfoOne getDefaultInstance() {
      return defaultInstance;
    }

    public TaskInfoOne getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaskInfoOne(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              weekNum_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              num_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              flag_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              stat_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              iD_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              dayNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MiscBean.internal_static_TaskInfoOne_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MiscBean.internal_static_TaskInfoOne_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MiscBean.TaskInfoOne.class, MiscBean.TaskInfoOne.Builder.class);
    }

    public static com.google.protobuf.Parser<TaskInfoOne> PARSER =
        new com.google.protobuf.AbstractParser<TaskInfoOne>() {
      public TaskInfoOne parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskInfoOne(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaskInfoOne> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 WeekNum = 1;
    public static final int WEEKNUM_FIELD_NUMBER = 1;
    private int weekNum_;
    /**
     * <code>required int32 WeekNum = 1;</code>
     */
    public boolean hasWeekNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 WeekNum = 1;</code>
     */
    public int getWeekNum() {
      return weekNum_;
    }

    // required int32 Num = 2;
    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    /**
     * <code>required int32 Num = 2;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 Num = 2;</code>
     */
    public int getNum() {
      return num_;
    }

    // required int32 Flag = 3;
    public static final int FLAG_FIELD_NUMBER = 3;
    private int flag_;
    /**
     * <code>required int32 Flag = 3;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 Flag = 3;</code>
     */
    public int getFlag() {
      return flag_;
    }

    // required int32 Stat = 4;
    public static final int STAT_FIELD_NUMBER = 4;
    private int stat_;
    /**
     * <code>required int32 Stat = 4;</code>
     */
    public boolean hasStat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 Stat = 4;</code>
     */
    public int getStat() {
      return stat_;
    }

    // required int32 ID = 5;
    public static final int ID_FIELD_NUMBER = 5;
    private int iD_;
    /**
     * <code>required int32 ID = 5;</code>
     */
    public boolean hasID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 ID = 5;</code>
     */
    public int getID() {
      return iD_;
    }

    // required int32 DayNum = 6;
    public static final int DAYNUM_FIELD_NUMBER = 6;
    private int dayNum_;
    /**
     * <code>required int32 DayNum = 6;</code>
     */
    public boolean hasDayNum() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 DayNum = 6;</code>
     */
    public int getDayNum() {
      return dayNum_;
    }

    private void initFields() {
      weekNum_ = 0;
      num_ = 0;
      flag_ = 0;
      stat_ = 0;
      iD_ = 0;
      dayNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWeekNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDayNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, weekNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, num_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, flag_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, stat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, iD_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, dayNum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, weekNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, flag_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, stat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, iD_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, dayNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static MiscBean.TaskInfoOne parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MiscBean.TaskInfoOne parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MiscBean.TaskInfoOne parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MiscBean.TaskInfoOne parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MiscBean.TaskInfoOne parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MiscBean.TaskInfoOne parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MiscBean.TaskInfoOne parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MiscBean.TaskInfoOne parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MiscBean.TaskInfoOne parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MiscBean.TaskInfoOne parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MiscBean.TaskInfoOne prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaskInfoOne}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MiscBean.TaskInfoOneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MiscBean.internal_static_TaskInfoOne_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MiscBean.internal_static_TaskInfoOne_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MiscBean.TaskInfoOne.class, MiscBean.TaskInfoOne.Builder.class);
      }

      // Construct using MiscBean.TaskInfoOne.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        weekNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        stat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        iD_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        dayNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MiscBean.internal_static_TaskInfoOne_descriptor;
      }

      public MiscBean.TaskInfoOne getDefaultInstanceForType() {
        return MiscBean.TaskInfoOne.getDefaultInstance();
      }

      public MiscBean.TaskInfoOne build() {
        MiscBean.TaskInfoOne result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MiscBean.TaskInfoOne buildPartial() {
        MiscBean.TaskInfoOne result = new MiscBean.TaskInfoOne(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.weekNum_ = weekNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.stat_ = stat_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.iD_ = iD_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.dayNum_ = dayNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MiscBean.TaskInfoOne) {
          return mergeFrom((MiscBean.TaskInfoOne)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MiscBean.TaskInfoOne other) {
        if (other == MiscBean.TaskInfoOne.getDefaultInstance()) return this;
        if (other.hasWeekNum()) {
          setWeekNum(other.getWeekNum());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasStat()) {
          setStat(other.getStat());
        }
        if (other.hasID()) {
          setID(other.getID());
        }
        if (other.hasDayNum()) {
          setDayNum(other.getDayNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWeekNum()) {
          
          return false;
        }
        if (!hasNum()) {
          
          return false;
        }
        if (!hasFlag()) {
          
          return false;
        }
        if (!hasStat()) {
          
          return false;
        }
        if (!hasID()) {
          
          return false;
        }
        if (!hasDayNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MiscBean.TaskInfoOne parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MiscBean.TaskInfoOne) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 WeekNum = 1;
      private int weekNum_ ;
      /**
       * <code>required int32 WeekNum = 1;</code>
       */
      public boolean hasWeekNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 WeekNum = 1;</code>
       */
      public int getWeekNum() {
        return weekNum_;
      }
      /**
       * <code>required int32 WeekNum = 1;</code>
       */
      public Builder setWeekNum(int value) {
        bitField0_ |= 0x00000001;
        weekNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 WeekNum = 1;</code>
       */
      public Builder clearWeekNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        weekNum_ = 0;
        onChanged();
        return this;
      }

      // required int32 Num = 2;
      private int num_ ;
      /**
       * <code>required int32 Num = 2;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 Num = 2;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 Num = 2;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000002;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Num = 2;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        onChanged();
        return this;
      }

      // required int32 Flag = 3;
      private int flag_ ;
      /**
       * <code>required int32 Flag = 3;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 Flag = 3;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <code>required int32 Flag = 3;</code>
       */
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000004;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Flag = 3;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000004);
        flag_ = 0;
        onChanged();
        return this;
      }

      // required int32 Stat = 4;
      private int stat_ ;
      /**
       * <code>required int32 Stat = 4;</code>
       */
      public boolean hasStat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 Stat = 4;</code>
       */
      public int getStat() {
        return stat_;
      }
      /**
       * <code>required int32 Stat = 4;</code>
       */
      public Builder setStat(int value) {
        bitField0_ |= 0x00000008;
        stat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Stat = 4;</code>
       */
      public Builder clearStat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        stat_ = 0;
        onChanged();
        return this;
      }

      // required int32 ID = 5;
      private int iD_ ;
      /**
       * <code>required int32 ID = 5;</code>
       */
      public boolean hasID() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 ID = 5;</code>
       */
      public int getID() {
        return iD_;
      }
      /**
       * <code>required int32 ID = 5;</code>
       */
      public Builder setID(int value) {
        bitField0_ |= 0x00000010;
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ID = 5;</code>
       */
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        iD_ = 0;
        onChanged();
        return this;
      }

      // required int32 DayNum = 6;
      private int dayNum_ ;
      /**
       * <code>required int32 DayNum = 6;</code>
       */
      public boolean hasDayNum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 DayNum = 6;</code>
       */
      public int getDayNum() {
        return dayNum_;
      }
      /**
       * <code>required int32 DayNum = 6;</code>
       */
      public Builder setDayNum(int value) {
        bitField0_ |= 0x00000020;
        dayNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 DayNum = 6;</code>
       */
      public Builder clearDayNum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        dayNum_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaskInfoOne)
    }

    static {
      defaultInstance = new TaskInfoOne(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TaskInfoOne)
  }

  public interface MiscTaskInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 Num = 1;
    /**
     * <code>required int32 Num = 1;</code>
     */
    boolean hasNum();
    /**
     * <code>required int32 Num = 1;</code>
     */
    int getNum();

    // repeated .TaskInfoOne One = 2;
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    java.util.List<MiscBean.TaskInfoOne> 
        getOneList();
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    MiscBean.TaskInfoOne getOne(int index);
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    int getOneCount();
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    java.util.List<? extends MiscBean.TaskInfoOneOrBuilder> 
        getOneOrBuilderList();
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    MiscBean.TaskInfoOneOrBuilder getOneOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MiscTaskInfo}
   */
  public static final class MiscTaskInfo extends
      com.google.protobuf.GeneratedMessage
      implements MiscTaskInfoOrBuilder {
    // Use MiscTaskInfo.newBuilder() to construct.
    private MiscTaskInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MiscTaskInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MiscTaskInfo defaultInstance;
    public static MiscTaskInfo getDefaultInstance() {
      return defaultInstance;
    }

    public MiscTaskInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MiscTaskInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              num_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                one_ = new java.util.ArrayList<MiscBean.TaskInfoOne>();
                mutable_bitField0_ |= 0x00000002;
              }
              one_.add(input.readMessage(MiscBean.TaskInfoOne.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          one_ = java.util.Collections.unmodifiableList(one_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MiscBean.internal_static_MiscTaskInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MiscBean.internal_static_MiscTaskInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MiscBean.MiscTaskInfo.class, MiscBean.MiscTaskInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<MiscTaskInfo> PARSER =
        new com.google.protobuf.AbstractParser<MiscTaskInfo>() {
      public MiscTaskInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MiscTaskInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MiscTaskInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 Num = 1;
    public static final int NUM_FIELD_NUMBER = 1;
    private int num_;
    /**
     * <code>required int32 Num = 1;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Num = 1;</code>
     */
    public int getNum() {
      return num_;
    }

    // repeated .TaskInfoOne One = 2;
    public static final int ONE_FIELD_NUMBER = 2;
    private java.util.List<MiscBean.TaskInfoOne> one_;
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    public java.util.List<MiscBean.TaskInfoOne> getOneList() {
      return one_;
    }
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    public java.util.List<? extends MiscBean.TaskInfoOneOrBuilder> 
        getOneOrBuilderList() {
      return one_;
    }
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    public int getOneCount() {
      return one_.size();
    }
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    public MiscBean.TaskInfoOne getOne(int index) {
      return one_.get(index);
    }
    /**
     * <code>repeated .TaskInfoOne One = 2;</code>
     */
    public MiscBean.TaskInfoOneOrBuilder getOneOrBuilder(
        int index) {
      return one_.get(index);
    }

    private void initFields() {
      num_ = 0;
      one_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOneCount(); i++) {
        if (!getOne(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, num_);
      }
      for (int i = 0; i < one_.size(); i++) {
        output.writeMessage(2, one_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num_);
      }
      for (int i = 0; i < one_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, one_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static MiscBean.MiscTaskInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MiscBean.MiscTaskInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MiscBean.MiscTaskInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MiscBean.MiscTaskInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MiscBean.MiscTaskInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MiscBean.MiscTaskInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MiscBean.MiscTaskInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MiscBean.MiscTaskInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MiscBean.MiscTaskInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MiscBean.MiscTaskInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MiscBean.MiscTaskInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MiscTaskInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MiscBean.MiscTaskInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MiscBean.internal_static_MiscTaskInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MiscBean.internal_static_MiscTaskInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MiscBean.MiscTaskInfo.class, MiscBean.MiscTaskInfo.Builder.class);
      }

      // Construct using MiscBean.MiscTaskInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (oneBuilder_ == null) {
          one_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          oneBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MiscBean.internal_static_MiscTaskInfo_descriptor;
      }

      public MiscBean.MiscTaskInfo getDefaultInstanceForType() {
        return MiscBean.MiscTaskInfo.getDefaultInstance();
      }

      public MiscBean.MiscTaskInfo build() {
        MiscBean.MiscTaskInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MiscBean.MiscTaskInfo buildPartial() {
        MiscBean.MiscTaskInfo result = new MiscBean.MiscTaskInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num_ = num_;
        if (oneBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            one_ = java.util.Collections.unmodifiableList(one_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.one_ = one_;
        } else {
          result.one_ = oneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MiscBean.MiscTaskInfo) {
          return mergeFrom((MiscBean.MiscTaskInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MiscBean.MiscTaskInfo other) {
        if (other == MiscBean.MiscTaskInfo.getDefaultInstance()) return this;
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (oneBuilder_ == null) {
          if (!other.one_.isEmpty()) {
            if (one_.isEmpty()) {
              one_ = other.one_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOneIsMutable();
              one_.addAll(other.one_);
            }
            onChanged();
          }
        } else {
          if (!other.one_.isEmpty()) {
            if (oneBuilder_.isEmpty()) {
              oneBuilder_.dispose();
              oneBuilder_ = null;
              one_ = other.one_;
              bitField0_ = (bitField0_ & ~0x00000002);
              oneBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOneFieldBuilder() : null;
            } else {
              oneBuilder_.addAllMessages(other.one_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNum()) {
          
          return false;
        }
        for (int i = 0; i < getOneCount(); i++) {
          if (!getOne(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MiscBean.MiscTaskInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MiscBean.MiscTaskInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 Num = 1;
      private int num_ ;
      /**
       * <code>required int32 Num = 1;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Num = 1;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 Num = 1;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000001;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Num = 1;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        onChanged();
        return this;
      }

      // repeated .TaskInfoOne One = 2;
      private java.util.List<MiscBean.TaskInfoOne> one_ =
        java.util.Collections.emptyList();
      private void ensureOneIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          one_ = new java.util.ArrayList<MiscBean.TaskInfoOne>(one_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          MiscBean.TaskInfoOne, MiscBean.TaskInfoOne.Builder, MiscBean.TaskInfoOneOrBuilder> oneBuilder_;

      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public java.util.List<MiscBean.TaskInfoOne> getOneList() {
        if (oneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(one_);
        } else {
          return oneBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public int getOneCount() {
        if (oneBuilder_ == null) {
          return one_.size();
        } else {
          return oneBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public MiscBean.TaskInfoOne getOne(int index) {
        if (oneBuilder_ == null) {
          return one_.get(index);
        } else {
          return oneBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder setOne(
          int index, MiscBean.TaskInfoOne value) {
        if (oneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneIsMutable();
          one_.set(index, value);
          onChanged();
        } else {
          oneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder setOne(
          int index, MiscBean.TaskInfoOne.Builder builderForValue) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          one_.set(index, builderForValue.build());
          onChanged();
        } else {
          oneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder addOne(MiscBean.TaskInfoOne value) {
        if (oneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneIsMutable();
          one_.add(value);
          onChanged();
        } else {
          oneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder addOne(
          int index, MiscBean.TaskInfoOne value) {
        if (oneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOneIsMutable();
          one_.add(index, value);
          onChanged();
        } else {
          oneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder addOne(
          MiscBean.TaskInfoOne.Builder builderForValue) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          one_.add(builderForValue.build());
          onChanged();
        } else {
          oneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder addOne(
          int index, MiscBean.TaskInfoOne.Builder builderForValue) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          one_.add(index, builderForValue.build());
          onChanged();
        } else {
          oneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder addAllOne(
          java.lang.Iterable<? extends MiscBean.TaskInfoOne> values) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          super.addAll(values, one_);
          onChanged();
        } else {
          oneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder clearOne() {
        if (oneBuilder_ == null) {
          one_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          oneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public Builder removeOne(int index) {
        if (oneBuilder_ == null) {
          ensureOneIsMutable();
          one_.remove(index);
          onChanged();
        } else {
          oneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public MiscBean.TaskInfoOne.Builder getOneBuilder(
          int index) {
        return getOneFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public MiscBean.TaskInfoOneOrBuilder getOneOrBuilder(
          int index) {
        if (oneBuilder_ == null) {
          return one_.get(index);  } else {
          return oneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public java.util.List<? extends MiscBean.TaskInfoOneOrBuilder> 
           getOneOrBuilderList() {
        if (oneBuilder_ != null) {
          return oneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(one_);
        }
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public MiscBean.TaskInfoOne.Builder addOneBuilder() {
        return getOneFieldBuilder().addBuilder(
            MiscBean.TaskInfoOne.getDefaultInstance());
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public MiscBean.TaskInfoOne.Builder addOneBuilder(
          int index) {
        return getOneFieldBuilder().addBuilder(
            index, MiscBean.TaskInfoOne.getDefaultInstance());
      }
      /**
       * <code>repeated .TaskInfoOne One = 2;</code>
       */
      public java.util.List<MiscBean.TaskInfoOne.Builder> 
           getOneBuilderList() {
        return getOneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          MiscBean.TaskInfoOne, MiscBean.TaskInfoOne.Builder, MiscBean.TaskInfoOneOrBuilder> 
          getOneFieldBuilder() {
        if (oneBuilder_ == null) {
          oneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              MiscBean.TaskInfoOne, MiscBean.TaskInfoOne.Builder, MiscBean.TaskInfoOneOrBuilder>(
                  one_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          one_ = null;
        }
        return oneBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MiscTaskInfo)
    }

    static {
      defaultInstance = new MiscTaskInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MiscTaskInfo)
  }

  public interface MiscOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .MiscTaskInfo TaskInfo = 1;
    /**
     * <code>required .MiscTaskInfo TaskInfo = 1;</code>
     */
    boolean hasTaskInfo();
    /**
     * <code>required .MiscTaskInfo TaskInfo = 1;</code>
     */
    MiscBean.MiscTaskInfo getTaskInfo();
    /**
     * <code>required .MiscTaskInfo TaskInfo = 1;</code>
     */
    MiscBean.MiscTaskInfoOrBuilder getTaskInfoOrBuilder();
  }
  /**
   * Protobuf type {@code Misc}
   */
  public static final class Misc extends
      com.google.protobuf.GeneratedMessage
      implements MiscOrBuilder {
    // Use Misc.newBuilder() to construct.
    private Misc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Misc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Misc defaultInstance;
    public static Misc getDefaultInstance() {
      return defaultInstance;
    }

    public Misc getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Misc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              MiscBean.MiscTaskInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = taskInfo_.toBuilder();
              }
              taskInfo_ = input.readMessage(MiscBean.MiscTaskInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(taskInfo_);
                taskInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MiscBean.internal_static_Misc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MiscBean.internal_static_Misc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MiscBean.Misc.class, MiscBean.Misc.Builder.class);
    }

    public static com.google.protobuf.Parser<Misc> PARSER =
        new com.google.protobuf.AbstractParser<Misc>() {
      public Misc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Misc(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Misc> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .MiscTaskInfo TaskInfo = 1;
    public static final int TASKINFO_FIELD_NUMBER = 1;
    private MiscBean.MiscTaskInfo taskInfo_;
    /**
     * <code>required .MiscTaskInfo TaskInfo = 1;</code>
     */
    public boolean hasTaskInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .MiscTaskInfo TaskInfo = 1;</code>
     */
    public MiscBean.MiscTaskInfo getTaskInfo() {
      return taskInfo_;
    }
    /**
     * <code>required .MiscTaskInfo TaskInfo = 1;</code>
     */
    public MiscBean.MiscTaskInfoOrBuilder getTaskInfoOrBuilder() {
      return taskInfo_;
    }

    private void initFields() {
      taskInfo_ = MiscBean.MiscTaskInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTaskInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTaskInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, taskInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, taskInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static MiscBean.Misc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MiscBean.Misc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MiscBean.Misc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MiscBean.Misc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MiscBean.Misc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MiscBean.Misc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MiscBean.Misc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MiscBean.Misc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MiscBean.Misc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MiscBean.Misc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MiscBean.Misc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Misc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MiscBean.MiscOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MiscBean.internal_static_Misc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MiscBean.internal_static_Misc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MiscBean.Misc.class, MiscBean.Misc.Builder.class);
      }

      // Construct using MiscBean.Misc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTaskInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (taskInfoBuilder_ == null) {
          taskInfo_ = MiscBean.MiscTaskInfo.getDefaultInstance();
        } else {
          taskInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MiscBean.internal_static_Misc_descriptor;
      }

      public MiscBean.Misc getDefaultInstanceForType() {
        return MiscBean.Misc.getDefaultInstance();
      }

      public MiscBean.Misc build() {
        MiscBean.Misc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MiscBean.Misc buildPartial() {
        MiscBean.Misc result = new MiscBean.Misc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (taskInfoBuilder_ == null) {
          result.taskInfo_ = taskInfo_;
        } else {
          result.taskInfo_ = taskInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MiscBean.Misc) {
          return mergeFrom((MiscBean.Misc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MiscBean.Misc other) {
        if (other == MiscBean.Misc.getDefaultInstance()) return this;
        if (other.hasTaskInfo()) {
          mergeTaskInfo(other.getTaskInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaskInfo()) {
          
          return false;
        }
        if (!getTaskInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MiscBean.Misc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MiscBean.Misc) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .MiscTaskInfo TaskInfo = 1;
      private MiscBean.MiscTaskInfo taskInfo_ = MiscBean.MiscTaskInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          MiscBean.MiscTaskInfo, MiscBean.MiscTaskInfo.Builder, MiscBean.MiscTaskInfoOrBuilder> taskInfoBuilder_;
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      public boolean hasTaskInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      public MiscBean.MiscTaskInfo getTaskInfo() {
        if (taskInfoBuilder_ == null) {
          return taskInfo_;
        } else {
          return taskInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      public Builder setTaskInfo(MiscBean.MiscTaskInfo value) {
        if (taskInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          taskInfo_ = value;
          onChanged();
        } else {
          taskInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      public Builder setTaskInfo(
          MiscBean.MiscTaskInfo.Builder builderForValue) {
        if (taskInfoBuilder_ == null) {
          taskInfo_ = builderForValue.build();
          onChanged();
        } else {
          taskInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      public Builder mergeTaskInfo(MiscBean.MiscTaskInfo value) {
        if (taskInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              taskInfo_ != MiscBean.MiscTaskInfo.getDefaultInstance()) {
            taskInfo_ =
              MiscBean.MiscTaskInfo.newBuilder(taskInfo_).mergeFrom(value).buildPartial();
          } else {
            taskInfo_ = value;
          }
          onChanged();
        } else {
          taskInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      public Builder clearTaskInfo() {
        if (taskInfoBuilder_ == null) {
          taskInfo_ = MiscBean.MiscTaskInfo.getDefaultInstance();
          onChanged();
        } else {
          taskInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      public MiscBean.MiscTaskInfo.Builder getTaskInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTaskInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      public MiscBean.MiscTaskInfoOrBuilder getTaskInfoOrBuilder() {
        if (taskInfoBuilder_ != null) {
          return taskInfoBuilder_.getMessageOrBuilder();
        } else {
          return taskInfo_;
        }
      }
      /**
       * <code>required .MiscTaskInfo TaskInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          MiscBean.MiscTaskInfo, MiscBean.MiscTaskInfo.Builder, MiscBean.MiscTaskInfoOrBuilder> 
          getTaskInfoFieldBuilder() {
        if (taskInfoBuilder_ == null) {
          taskInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              MiscBean.MiscTaskInfo, MiscBean.MiscTaskInfo.Builder, MiscBean.MiscTaskInfoOrBuilder>(
                  taskInfo_,
                  getParentForChildren(),
                  isClean());
          taskInfo_ = null;
        }
        return taskInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Misc)
    }

    static {
      defaultInstance = new Misc(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Misc)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskInfoOne_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TaskInfoOne_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MiscTaskInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MiscTaskInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Misc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Misc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nMisc.proto\"c\n\013TaskInfoOne\022\017\n\007WeekNum\030\001" +
      " \002(\005\022\013\n\003Num\030\002 \002(\005\022\014\n\004Flag\030\003 \002(\005\022\014\n\004Stat\030" +
      "\004 \002(\005\022\n\n\002ID\030\005 \002(\005\022\016\n\006DayNum\030\006 \002(\005\"6\n\014Mis" +
      "cTaskInfo\022\013\n\003Num\030\001 \002(\005\022\031\n\003One\030\002 \003(\0132\014.Ta" +
      "skInfoOne\"\'\n\004Misc\022\037\n\010TaskInfo\030\001 \002(\0132\r.Mi" +
      "scTaskInfoB\nB\010MiscBean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TaskInfoOne_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TaskInfoOne_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TaskInfoOne_descriptor,
              new java.lang.String[] { "WeekNum", "Num", "Flag", "Stat", "ID", "DayNum", });
          internal_static_MiscTaskInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MiscTaskInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MiscTaskInfo_descriptor,
              new java.lang.String[] { "Num", "One", });
          internal_static_Misc_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Misc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Misc_descriptor,
              new java.lang.String[] { "TaskInfo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
