// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs.proto

public final class RichManBean {
  private RichManBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MSG_TYPE}
   *
   * <pre>
   * 消息类型
   * </pre>
   */
  public enum MSG_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN_REQ = 5;</code>
     */
    LOGIN_REQ(0, 5),
    /**
     * <code>LOGIN_RES = 6;</code>
     */
    LOGIN_RES(1, 6),
    /**
     * <code>HEART_REQ = 9;</code>
     *
     * <pre>
     * 心跳包请求
     * </pre>
     */
    HEART_REQ(2, 9),
    /**
     * <code>HEART_RES = 10;</code>
     *
     * <pre>
     * 心跳包回复
     * </pre>
     */
    HEART_RES(3, 10),
    ;

    /**
     * <code>LOGIN_REQ = 5;</code>
     */
    public static final int LOGIN_REQ_VALUE = 5;
    /**
     * <code>LOGIN_RES = 6;</code>
     */
    public static final int LOGIN_RES_VALUE = 6;
    /**
     * <code>HEART_REQ = 9;</code>
     *
     * <pre>
     * 心跳包请求
     * </pre>
     */
    public static final int HEART_REQ_VALUE = 9;
    /**
     * <code>HEART_RES = 10;</code>
     *
     * <pre>
     * 心跳包回复
     * </pre>
     */
    public static final int HEART_RES_VALUE = 10;


    public final int getNumber() { return value; }

    public static MSG_TYPE valueOf(int value) {
      switch (value) {
        case 5: return LOGIN_REQ;
        case 6: return LOGIN_RES;
        case 9: return HEART_REQ;
        case 10: return HEART_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MSG_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MSG_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MSG_TYPE>() {
            public MSG_TYPE findValueByNumber(int number) {
              return MSG_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RichManBean.getDescriptor().getEnumTypes().get(0);
    }

    private static final MSG_TYPE[] VALUES = values();

    public static MSG_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MSG_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MSG_TYPE)
  }

  public interface CsHeartReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 SvrTime = 1;
    /**
     * <code>required int32 SvrTime = 1;</code>
     *
     * <pre>
     * 	
     * </pre>
     */
    boolean hasSvrTime();
    /**
     * <code>required int32 SvrTime = 1;</code>
     *
     * <pre>
     * 	
     * </pre>
     */
    int getSvrTime();
  }
  /**
   * Protobuf type {@code CsHeartReq}
   *
   * <pre>
   * 心跳包请求 --客户端把当前服务器时间返回给服务器
   * </pre>
   */
  public static final class CsHeartReq extends
      com.google.protobuf.GeneratedMessage
      implements CsHeartReqOrBuilder {
    // Use CsHeartReq.newBuilder() to construct.
    private CsHeartReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CsHeartReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CsHeartReq defaultInstance;
    public static CsHeartReq getDefaultInstance() {
      return defaultInstance;
    }

    public CsHeartReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CsHeartReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              svrTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RichManBean.internal_static_CsHeartReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RichManBean.internal_static_CsHeartReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RichManBean.CsHeartReq.class, RichManBean.CsHeartReq.Builder.class);
    }

    public static com.google.protobuf.Parser<CsHeartReq> PARSER =
        new com.google.protobuf.AbstractParser<CsHeartReq>() {
      public CsHeartReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CsHeartReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CsHeartReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 SvrTime = 1;
    public static final int SVRTIME_FIELD_NUMBER = 1;
    private int svrTime_;
    /**
     * <code>required int32 SvrTime = 1;</code>
     *
     * <pre>
     * 	
     * </pre>
     */
    public boolean hasSvrTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 SvrTime = 1;</code>
     *
     * <pre>
     * 	
     * </pre>
     */
    public int getSvrTime() {
      return svrTime_;
    }

    private void initFields() {
      svrTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSvrTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, svrTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, svrTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RichManBean.CsHeartReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RichManBean.CsHeartReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RichManBean.CsHeartReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RichManBean.CsHeartReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RichManBean.CsHeartReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RichManBean.CsHeartReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RichManBean.CsHeartReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RichManBean.CsHeartReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RichManBean.CsHeartReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RichManBean.CsHeartReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RichManBean.CsHeartReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CsHeartReq}
     *
     * <pre>
     * 心跳包请求 --客户端把当前服务器时间返回给服务器
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RichManBean.CsHeartReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RichManBean.internal_static_CsHeartReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RichManBean.internal_static_CsHeartReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RichManBean.CsHeartReq.class, RichManBean.CsHeartReq.Builder.class);
      }

      // Construct using RichManBean.CsHeartReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        svrTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RichManBean.internal_static_CsHeartReq_descriptor;
      }

      public RichManBean.CsHeartReq getDefaultInstanceForType() {
        return RichManBean.CsHeartReq.getDefaultInstance();
      }

      public RichManBean.CsHeartReq build() {
        RichManBean.CsHeartReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RichManBean.CsHeartReq buildPartial() {
        RichManBean.CsHeartReq result = new RichManBean.CsHeartReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.svrTime_ = svrTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RichManBean.CsHeartReq) {
          return mergeFrom((RichManBean.CsHeartReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RichManBean.CsHeartReq other) {
        if (other == RichManBean.CsHeartReq.getDefaultInstance()) return this;
        if (other.hasSvrTime()) {
          setSvrTime(other.getSvrTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSvrTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RichManBean.CsHeartReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RichManBean.CsHeartReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 SvrTime = 1;
      private int svrTime_ ;
      /**
       * <code>required int32 SvrTime = 1;</code>
       *
       * <pre>
       * 	
       * </pre>
       */
      public boolean hasSvrTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 SvrTime = 1;</code>
       *
       * <pre>
       * 	
       * </pre>
       */
      public int getSvrTime() {
        return svrTime_;
      }
      /**
       * <code>required int32 SvrTime = 1;</code>
       *
       * <pre>
       * 	
       * </pre>
       */
      public Builder setSvrTime(int value) {
        bitField0_ |= 0x00000001;
        svrTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 SvrTime = 1;</code>
       *
       * <pre>
       * 	
       * </pre>
       */
      public Builder clearSvrTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        svrTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CsHeartReq)
    }

    static {
      defaultInstance = new CsHeartReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CsHeartReq)
  }

  public interface CsHeartResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 SvrTime = 1;
    /**
     * <code>required int32 SvrTime = 1;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    boolean hasSvrTime();
    /**
     * <code>required int32 SvrTime = 1;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    int getSvrTime();

    // required int32 MessageCount = 2;
    /**
     * <code>required int32 MessageCount = 2;</code>
     *
     * <pre>
     *当前未读聊天数量	
     * </pre>
     */
    boolean hasMessageCount();
    /**
     * <code>required int32 MessageCount = 2;</code>
     *
     * <pre>
     *当前未读聊天数量	
     * </pre>
     */
    int getMessageCount();
  }
  /**
   * Protobuf type {@code CsHeartRes}
   *
   * <pre>
   * 心跳包回复 --服务器会根据请求中的时间误差来调整 发给客户端新的服务器时间 小于等于-不用调整 大于0表示服务器时间
   * </pre>
   */
  public static final class CsHeartRes extends
      com.google.protobuf.GeneratedMessage
      implements CsHeartResOrBuilder {
    // Use CsHeartRes.newBuilder() to construct.
    private CsHeartRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CsHeartRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CsHeartRes defaultInstance;
    public static CsHeartRes getDefaultInstance() {
      return defaultInstance;
    }

    public CsHeartRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CsHeartRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              svrTime_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              messageCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RichManBean.internal_static_CsHeartRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RichManBean.internal_static_CsHeartRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RichManBean.CsHeartRes.class, RichManBean.CsHeartRes.Builder.class);
    }

    public static com.google.protobuf.Parser<CsHeartRes> PARSER =
        new com.google.protobuf.AbstractParser<CsHeartRes>() {
      public CsHeartRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CsHeartRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CsHeartRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 SvrTime = 1;
    public static final int SVRTIME_FIELD_NUMBER = 1;
    private int svrTime_;
    /**
     * <code>required int32 SvrTime = 1;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public boolean hasSvrTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 SvrTime = 1;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public int getSvrTime() {
      return svrTime_;
    }

    // required int32 MessageCount = 2;
    public static final int MESSAGECOUNT_FIELD_NUMBER = 2;
    private int messageCount_;
    /**
     * <code>required int32 MessageCount = 2;</code>
     *
     * <pre>
     *当前未读聊天数量	
     * </pre>
     */
    public boolean hasMessageCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 MessageCount = 2;</code>
     *
     * <pre>
     *当前未读聊天数量	
     * </pre>
     */
    public int getMessageCount() {
      return messageCount_;
    }

    private void initFields() {
      svrTime_ = 0;
      messageCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSvrTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, svrTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, messageCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, svrTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RichManBean.CsHeartRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RichManBean.CsHeartRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RichManBean.CsHeartRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RichManBean.CsHeartRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RichManBean.CsHeartRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RichManBean.CsHeartRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RichManBean.CsHeartRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RichManBean.CsHeartRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RichManBean.CsHeartRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RichManBean.CsHeartRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RichManBean.CsHeartRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CsHeartRes}
     *
     * <pre>
     * 心跳包回复 --服务器会根据请求中的时间误差来调整 发给客户端新的服务器时间 小于等于-不用调整 大于0表示服务器时间
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RichManBean.CsHeartResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RichManBean.internal_static_CsHeartRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RichManBean.internal_static_CsHeartRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RichManBean.CsHeartRes.class, RichManBean.CsHeartRes.Builder.class);
      }

      // Construct using RichManBean.CsHeartRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        svrTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RichManBean.internal_static_CsHeartRes_descriptor;
      }

      public RichManBean.CsHeartRes getDefaultInstanceForType() {
        return RichManBean.CsHeartRes.getDefaultInstance();
      }

      public RichManBean.CsHeartRes build() {
        RichManBean.CsHeartRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RichManBean.CsHeartRes buildPartial() {
        RichManBean.CsHeartRes result = new RichManBean.CsHeartRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.svrTime_ = svrTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageCount_ = messageCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RichManBean.CsHeartRes) {
          return mergeFrom((RichManBean.CsHeartRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RichManBean.CsHeartRes other) {
        if (other == RichManBean.CsHeartRes.getDefaultInstance()) return this;
        if (other.hasSvrTime()) {
          setSvrTime(other.getSvrTime());
        }
        if (other.hasMessageCount()) {
          setMessageCount(other.getMessageCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSvrTime()) {
          
          return false;
        }
        if (!hasMessageCount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RichManBean.CsHeartRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RichManBean.CsHeartRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 SvrTime = 1;
      private int svrTime_ ;
      /**
       * <code>required int32 SvrTime = 1;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public boolean hasSvrTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 SvrTime = 1;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public int getSvrTime() {
        return svrTime_;
      }
      /**
       * <code>required int32 SvrTime = 1;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setSvrTime(int value) {
        bitField0_ |= 0x00000001;
        svrTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 SvrTime = 1;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder clearSvrTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        svrTime_ = 0;
        onChanged();
        return this;
      }

      // required int32 MessageCount = 2;
      private int messageCount_ ;
      /**
       * <code>required int32 MessageCount = 2;</code>
       *
       * <pre>
       *当前未读聊天数量	
       * </pre>
       */
      public boolean hasMessageCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 MessageCount = 2;</code>
       *
       * <pre>
       *当前未读聊天数量	
       * </pre>
       */
      public int getMessageCount() {
        return messageCount_;
      }
      /**
       * <code>required int32 MessageCount = 2;</code>
       *
       * <pre>
       *当前未读聊天数量	
       * </pre>
       */
      public Builder setMessageCount(int value) {
        bitField0_ |= 0x00000002;
        messageCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 MessageCount = 2;</code>
       *
       * <pre>
       *当前未读聊天数量	
       * </pre>
       */
      public Builder clearMessageCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageCount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CsHeartRes)
    }

    static {
      defaultInstance = new CsHeartRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CsHeartRes)
  }

  public interface LoginReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 Uin = 1;
    /**
     * <code>required int32 Uin = 1;</code>
     */
    boolean hasUin();
    /**
     * <code>required int32 Uin = 1;</code>
     */
    int getUin();

    // required string AccName = 2;
    /**
     * <code>required string AccName = 2;</code>
     */
    boolean hasAccName();
    /**
     * <code>required string AccName = 2;</code>
     */
    java.lang.String getAccName();
    /**
     * <code>required string AccName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccNameBytes();

    // required string Enc = 3;
    /**
     * <code>required string Enc = 3;</code>
     */
    boolean hasEnc();
    /**
     * <code>required string Enc = 3;</code>
     */
    java.lang.String getEnc();
    /**
     * <code>required string Enc = 3;</code>
     */
    com.google.protobuf.ByteString
        getEncBytes();
  }
  /**
   * Protobuf type {@code LoginReq}
   */
  public static final class LoginReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginReqOrBuilder {
    // Use LoginReq.newBuilder() to construct.
    private LoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginReq defaultInstance;
    public static LoginReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uin_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              accName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              enc_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RichManBean.internal_static_LoginReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RichManBean.internal_static_LoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RichManBean.LoginReq.class, RichManBean.LoginReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginReq>() {
      public LoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 Uin = 1;
    public static final int UIN_FIELD_NUMBER = 1;
    private int uin_;
    /**
     * <code>required int32 Uin = 1;</code>
     */
    public boolean hasUin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Uin = 1;</code>
     */
    public int getUin() {
      return uin_;
    }

    // required string AccName = 2;
    public static final int ACCNAME_FIELD_NUMBER = 2;
    private java.lang.Object accName_;
    /**
     * <code>required string AccName = 2;</code>
     */
    public boolean hasAccName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string AccName = 2;</code>
     */
    public java.lang.String getAccName() {
      java.lang.Object ref = accName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string AccName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccNameBytes() {
      java.lang.Object ref = accName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string Enc = 3;
    public static final int ENC_FIELD_NUMBER = 3;
    private java.lang.Object enc_;
    /**
     * <code>required string Enc = 3;</code>
     */
    public boolean hasEnc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string Enc = 3;</code>
     */
    public java.lang.String getEnc() {
      java.lang.Object ref = enc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          enc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Enc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEncBytes() {
      java.lang.Object ref = enc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uin_ = 0;
      accName_ = "";
      enc_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEncBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEncBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RichManBean.LoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RichManBean.LoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RichManBean.LoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RichManBean.LoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RichManBean.LoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RichManBean.LoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RichManBean.LoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RichManBean.LoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RichManBean.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RichManBean.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RichManBean.LoginReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RichManBean.LoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RichManBean.internal_static_LoginReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RichManBean.internal_static_LoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RichManBean.LoginReq.class, RichManBean.LoginReq.Builder.class);
      }

      // Construct using RichManBean.LoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        enc_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RichManBean.internal_static_LoginReq_descriptor;
      }

      public RichManBean.LoginReq getDefaultInstanceForType() {
        return RichManBean.LoginReq.getDefaultInstance();
      }

      public RichManBean.LoginReq build() {
        RichManBean.LoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RichManBean.LoginReq buildPartial() {
        RichManBean.LoginReq result = new RichManBean.LoginReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uin_ = uin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accName_ = accName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.enc_ = enc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RichManBean.LoginReq) {
          return mergeFrom((RichManBean.LoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RichManBean.LoginReq other) {
        if (other == RichManBean.LoginReq.getDefaultInstance()) return this;
        if (other.hasUin()) {
          setUin(other.getUin());
        }
        if (other.hasAccName()) {
          bitField0_ |= 0x00000002;
          accName_ = other.accName_;
          onChanged();
        }
        if (other.hasEnc()) {
          bitField0_ |= 0x00000004;
          enc_ = other.enc_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUin()) {
          
          return false;
        }
        if (!hasAccName()) {
          
          return false;
        }
        if (!hasEnc()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RichManBean.LoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RichManBean.LoginReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 Uin = 1;
      private int uin_ ;
      /**
       * <code>required int32 Uin = 1;</code>
       */
      public boolean hasUin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Uin = 1;</code>
       */
      public int getUin() {
        return uin_;
      }
      /**
       * <code>required int32 Uin = 1;</code>
       */
      public Builder setUin(int value) {
        bitField0_ |= 0x00000001;
        uin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Uin = 1;</code>
       */
      public Builder clearUin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uin_ = 0;
        onChanged();
        return this;
      }

      // required string AccName = 2;
      private java.lang.Object accName_ = "";
      /**
       * <code>required string AccName = 2;</code>
       */
      public boolean hasAccName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string AccName = 2;</code>
       */
      public java.lang.String getAccName() {
        java.lang.Object ref = accName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string AccName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccNameBytes() {
        java.lang.Object ref = accName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string AccName = 2;</code>
       */
      public Builder setAccName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string AccName = 2;</code>
       */
      public Builder clearAccName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accName_ = getDefaultInstance().getAccName();
        onChanged();
        return this;
      }
      /**
       * <code>required string AccName = 2;</code>
       */
      public Builder setAccNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accName_ = value;
        onChanged();
        return this;
      }

      // required string Enc = 3;
      private java.lang.Object enc_ = "";
      /**
       * <code>required string Enc = 3;</code>
       */
      public boolean hasEnc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string Enc = 3;</code>
       */
      public java.lang.String getEnc() {
        java.lang.Object ref = enc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          enc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Enc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEncBytes() {
        java.lang.Object ref = enc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          enc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Enc = 3;</code>
       */
      public Builder setEnc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        enc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Enc = 3;</code>
       */
      public Builder clearEnc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        enc_ = getDefaultInstance().getEnc();
        onChanged();
        return this;
      }
      /**
       * <code>required string Enc = 3;</code>
       */
      public Builder setEncBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        enc_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoginReq)
    }

    static {
      defaultInstance = new LoginReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LoginReq)
  }

  public interface LoginResOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 Succ = 1;
    /**
     * <code>required int32 Succ = 1;</code>
     *
     * <pre>
     *1-成功
     * </pre>
     */
    boolean hasSucc();
    /**
     * <code>required int32 Succ = 1;</code>
     *
     * <pre>
     *1-成功
     * </pre>
     */
    int getSucc();

    // required int32 MemID = 2;
    /**
     * <code>required int32 MemID = 2;</code>
     *
     * <pre>
     * 角色服务器内存ID
     * </pre>
     */
    boolean hasMemID();
    /**
     * <code>required int32 MemID = 2;</code>
     *
     * <pre>
     * 角色服务器内存ID
     * </pre>
     */
    int getMemID();

    // required int32 SvrTime = 4;
    /**
     * <code>required int32 SvrTime = 4;</code>
     *
     * <pre>
     *required PlayerData PlayerData=3;	// 角色数据
     * </pre>
     */
    boolean hasSvrTime();
    /**
     * <code>required int32 SvrTime = 4;</code>
     *
     * <pre>
     *required PlayerData PlayerData=3;	// 角色数据
     * </pre>
     */
    int getSvrTime();

    // required int32 IsSelectCamp = 5;
    /**
     * <code>required int32 IsSelectCamp = 5;</code>
     *
     * <pre>
     * 是否选择了阵营 1-是
     * </pre>
     */
    boolean hasIsSelectCamp();
    /**
     * <code>required int32 IsSelectCamp = 5;</code>
     *
     * <pre>
     * 是否选择了阵营 1-是
     * </pre>
     */
    int getIsSelectCamp();

    // required uint32 LoginSeq = 6;
    /**
     * <code>required uint32 LoginSeq = 6;</code>
     *
     * <pre>
     * 第几次登录 第一次登录为1
     * </pre>
     */
    boolean hasLoginSeq();
    /**
     * <code>required uint32 LoginSeq = 6;</code>
     *
     * <pre>
     * 第几次登录 第一次登录为1
     * </pre>
     */
    int getLoginSeq();

    // required int32 RegTaskDay = 7;
    /**
     * <code>required int32 RegTaskDay = 7;</code>
     *
     * <pre>
     * 注册活动当前天数
     * </pre>
     */
    boolean hasRegTaskDay();
    /**
     * <code>required int32 RegTaskDay = 7;</code>
     *
     * <pre>
     * 注册活动当前天数
     * </pre>
     */
    int getRegTaskDay();
  }
  /**
   * Protobuf type {@code LoginRes}
   */
  public static final class LoginRes extends
      com.google.protobuf.GeneratedMessage
      implements LoginResOrBuilder {
    // Use LoginRes.newBuilder() to construct.
    private LoginRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginRes defaultInstance;
    public static LoginRes getDefaultInstance() {
      return defaultInstance;
    }

    public LoginRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              succ_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              memID_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              svrTime_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              isSelectCamp_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              loginSeq_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              regTaskDay_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RichManBean.internal_static_LoginRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RichManBean.internal_static_LoginRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RichManBean.LoginRes.class, RichManBean.LoginRes.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginRes> PARSER =
        new com.google.protobuf.AbstractParser<LoginRes>() {
      public LoginRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 Succ = 1;
    public static final int SUCC_FIELD_NUMBER = 1;
    private int succ_;
    /**
     * <code>required int32 Succ = 1;</code>
     *
     * <pre>
     *1-成功
     * </pre>
     */
    public boolean hasSucc() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Succ = 1;</code>
     *
     * <pre>
     *1-成功
     * </pre>
     */
    public int getSucc() {
      return succ_;
    }

    // required int32 MemID = 2;
    public static final int MEMID_FIELD_NUMBER = 2;
    private int memID_;
    /**
     * <code>required int32 MemID = 2;</code>
     *
     * <pre>
     * 角色服务器内存ID
     * </pre>
     */
    public boolean hasMemID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 MemID = 2;</code>
     *
     * <pre>
     * 角色服务器内存ID
     * </pre>
     */
    public int getMemID() {
      return memID_;
    }

    // required int32 SvrTime = 4;
    public static final int SVRTIME_FIELD_NUMBER = 4;
    private int svrTime_;
    /**
     * <code>required int32 SvrTime = 4;</code>
     *
     * <pre>
     *required PlayerData PlayerData=3;	// 角色数据
     * </pre>
     */
    public boolean hasSvrTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 SvrTime = 4;</code>
     *
     * <pre>
     *required PlayerData PlayerData=3;	// 角色数据
     * </pre>
     */
    public int getSvrTime() {
      return svrTime_;
    }

    // required int32 IsSelectCamp = 5;
    public static final int ISSELECTCAMP_FIELD_NUMBER = 5;
    private int isSelectCamp_;
    /**
     * <code>required int32 IsSelectCamp = 5;</code>
     *
     * <pre>
     * 是否选择了阵营 1-是
     * </pre>
     */
    public boolean hasIsSelectCamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 IsSelectCamp = 5;</code>
     *
     * <pre>
     * 是否选择了阵营 1-是
     * </pre>
     */
    public int getIsSelectCamp() {
      return isSelectCamp_;
    }

    // required uint32 LoginSeq = 6;
    public static final int LOGINSEQ_FIELD_NUMBER = 6;
    private int loginSeq_;
    /**
     * <code>required uint32 LoginSeq = 6;</code>
     *
     * <pre>
     * 第几次登录 第一次登录为1
     * </pre>
     */
    public boolean hasLoginSeq() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 LoginSeq = 6;</code>
     *
     * <pre>
     * 第几次登录 第一次登录为1
     * </pre>
     */
    public int getLoginSeq() {
      return loginSeq_;
    }

    // required int32 RegTaskDay = 7;
    public static final int REGTASKDAY_FIELD_NUMBER = 7;
    private int regTaskDay_;
    /**
     * <code>required int32 RegTaskDay = 7;</code>
     *
     * <pre>
     * 注册活动当前天数
     * </pre>
     */
    public boolean hasRegTaskDay() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 RegTaskDay = 7;</code>
     *
     * <pre>
     * 注册活动当前天数
     * </pre>
     */
    public int getRegTaskDay() {
      return regTaskDay_;
    }

    private void initFields() {
      succ_ = 0;
      memID_ = 0;
      svrTime_ = 0;
      isSelectCamp_ = 0;
      loginSeq_ = 0;
      regTaskDay_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSucc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMemID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSvrTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsSelectCamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoginSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRegTaskDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, succ_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, memID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, svrTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, isSelectCamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(6, loginSeq_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, regTaskDay_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, succ_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, memID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, svrTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, isSelectCamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, loginSeq_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, regTaskDay_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RichManBean.LoginRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RichManBean.LoginRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RichManBean.LoginRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RichManBean.LoginRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RichManBean.LoginRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RichManBean.LoginRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RichManBean.LoginRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RichManBean.LoginRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RichManBean.LoginRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RichManBean.LoginRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RichManBean.LoginRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RichManBean.LoginResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RichManBean.internal_static_LoginRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RichManBean.internal_static_LoginRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RichManBean.LoginRes.class, RichManBean.LoginRes.Builder.class);
      }

      // Construct using RichManBean.LoginRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        succ_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        memID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        svrTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        isSelectCamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        loginSeq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        regTaskDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RichManBean.internal_static_LoginRes_descriptor;
      }

      public RichManBean.LoginRes getDefaultInstanceForType() {
        return RichManBean.LoginRes.getDefaultInstance();
      }

      public RichManBean.LoginRes build() {
        RichManBean.LoginRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RichManBean.LoginRes buildPartial() {
        RichManBean.LoginRes result = new RichManBean.LoginRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.succ_ = succ_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.memID_ = memID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.svrTime_ = svrTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isSelectCamp_ = isSelectCamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.loginSeq_ = loginSeq_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.regTaskDay_ = regTaskDay_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RichManBean.LoginRes) {
          return mergeFrom((RichManBean.LoginRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RichManBean.LoginRes other) {
        if (other == RichManBean.LoginRes.getDefaultInstance()) return this;
        if (other.hasSucc()) {
          setSucc(other.getSucc());
        }
        if (other.hasMemID()) {
          setMemID(other.getMemID());
        }
        if (other.hasSvrTime()) {
          setSvrTime(other.getSvrTime());
        }
        if (other.hasIsSelectCamp()) {
          setIsSelectCamp(other.getIsSelectCamp());
        }
        if (other.hasLoginSeq()) {
          setLoginSeq(other.getLoginSeq());
        }
        if (other.hasRegTaskDay()) {
          setRegTaskDay(other.getRegTaskDay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSucc()) {
          
          return false;
        }
        if (!hasMemID()) {
          
          return false;
        }
        if (!hasSvrTime()) {
          
          return false;
        }
        if (!hasIsSelectCamp()) {
          
          return false;
        }
        if (!hasLoginSeq()) {
          
          return false;
        }
        if (!hasRegTaskDay()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RichManBean.LoginRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RichManBean.LoginRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 Succ = 1;
      private int succ_ ;
      /**
       * <code>required int32 Succ = 1;</code>
       *
       * <pre>
       *1-成功
       * </pre>
       */
      public boolean hasSucc() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Succ = 1;</code>
       *
       * <pre>
       *1-成功
       * </pre>
       */
      public int getSucc() {
        return succ_;
      }
      /**
       * <code>required int32 Succ = 1;</code>
       *
       * <pre>
       *1-成功
       * </pre>
       */
      public Builder setSucc(int value) {
        bitField0_ |= 0x00000001;
        succ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Succ = 1;</code>
       *
       * <pre>
       *1-成功
       * </pre>
       */
      public Builder clearSucc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        succ_ = 0;
        onChanged();
        return this;
      }

      // required int32 MemID = 2;
      private int memID_ ;
      /**
       * <code>required int32 MemID = 2;</code>
       *
       * <pre>
       * 角色服务器内存ID
       * </pre>
       */
      public boolean hasMemID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 MemID = 2;</code>
       *
       * <pre>
       * 角色服务器内存ID
       * </pre>
       */
      public int getMemID() {
        return memID_;
      }
      /**
       * <code>required int32 MemID = 2;</code>
       *
       * <pre>
       * 角色服务器内存ID
       * </pre>
       */
      public Builder setMemID(int value) {
        bitField0_ |= 0x00000002;
        memID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 MemID = 2;</code>
       *
       * <pre>
       * 角色服务器内存ID
       * </pre>
       */
      public Builder clearMemID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        memID_ = 0;
        onChanged();
        return this;
      }

      // required int32 SvrTime = 4;
      private int svrTime_ ;
      /**
       * <code>required int32 SvrTime = 4;</code>
       *
       * <pre>
       *required PlayerData PlayerData=3;	// 角色数据
       * </pre>
       */
      public boolean hasSvrTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 SvrTime = 4;</code>
       *
       * <pre>
       *required PlayerData PlayerData=3;	// 角色数据
       * </pre>
       */
      public int getSvrTime() {
        return svrTime_;
      }
      /**
       * <code>required int32 SvrTime = 4;</code>
       *
       * <pre>
       *required PlayerData PlayerData=3;	// 角色数据
       * </pre>
       */
      public Builder setSvrTime(int value) {
        bitField0_ |= 0x00000004;
        svrTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 SvrTime = 4;</code>
       *
       * <pre>
       *required PlayerData PlayerData=3;	// 角色数据
       * </pre>
       */
      public Builder clearSvrTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        svrTime_ = 0;
        onChanged();
        return this;
      }

      // required int32 IsSelectCamp = 5;
      private int isSelectCamp_ ;
      /**
       * <code>required int32 IsSelectCamp = 5;</code>
       *
       * <pre>
       * 是否选择了阵营 1-是
       * </pre>
       */
      public boolean hasIsSelectCamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 IsSelectCamp = 5;</code>
       *
       * <pre>
       * 是否选择了阵营 1-是
       * </pre>
       */
      public int getIsSelectCamp() {
        return isSelectCamp_;
      }
      /**
       * <code>required int32 IsSelectCamp = 5;</code>
       *
       * <pre>
       * 是否选择了阵营 1-是
       * </pre>
       */
      public Builder setIsSelectCamp(int value) {
        bitField0_ |= 0x00000008;
        isSelectCamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 IsSelectCamp = 5;</code>
       *
       * <pre>
       * 是否选择了阵营 1-是
       * </pre>
       */
      public Builder clearIsSelectCamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isSelectCamp_ = 0;
        onChanged();
        return this;
      }

      // required uint32 LoginSeq = 6;
      private int loginSeq_ ;
      /**
       * <code>required uint32 LoginSeq = 6;</code>
       *
       * <pre>
       * 第几次登录 第一次登录为1
       * </pre>
       */
      public boolean hasLoginSeq() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 LoginSeq = 6;</code>
       *
       * <pre>
       * 第几次登录 第一次登录为1
       * </pre>
       */
      public int getLoginSeq() {
        return loginSeq_;
      }
      /**
       * <code>required uint32 LoginSeq = 6;</code>
       *
       * <pre>
       * 第几次登录 第一次登录为1
       * </pre>
       */
      public Builder setLoginSeq(int value) {
        bitField0_ |= 0x00000010;
        loginSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 LoginSeq = 6;</code>
       *
       * <pre>
       * 第几次登录 第一次登录为1
       * </pre>
       */
      public Builder clearLoginSeq() {
        bitField0_ = (bitField0_ & ~0x00000010);
        loginSeq_ = 0;
        onChanged();
        return this;
      }

      // required int32 RegTaskDay = 7;
      private int regTaskDay_ ;
      /**
       * <code>required int32 RegTaskDay = 7;</code>
       *
       * <pre>
       * 注册活动当前天数
       * </pre>
       */
      public boolean hasRegTaskDay() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 RegTaskDay = 7;</code>
       *
       * <pre>
       * 注册活动当前天数
       * </pre>
       */
      public int getRegTaskDay() {
        return regTaskDay_;
      }
      /**
       * <code>required int32 RegTaskDay = 7;</code>
       *
       * <pre>
       * 注册活动当前天数
       * </pre>
       */
      public Builder setRegTaskDay(int value) {
        bitField0_ |= 0x00000020;
        regTaskDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 RegTaskDay = 7;</code>
       *
       * <pre>
       * 注册活动当前天数
       * </pre>
       */
      public Builder clearRegTaskDay() {
        bitField0_ = (bitField0_ & ~0x00000020);
        regTaskDay_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoginRes)
    }

    static {
      defaultInstance = new LoginRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LoginRes)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CsHeartReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CsHeartReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CsHeartRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CsHeartRes_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010cs.proto\"\035\n\nCsHeartReq\022\017\n\007SvrTime\030\001 \002(" +
      "\005\"3\n\nCsHeartRes\022\017\n\007SvrTime\030\001 \002(\005\022\024\n\014Mess" +
      "ageCount\030\002 \002(\005\"5\n\010LoginReq\022\013\n\003Uin\030\001 \002(\005\022" +
      "\017\n\007AccName\030\002 \002(\t\022\013\n\003Enc\030\003 \002(\t\"t\n\010LoginRe" +
      "s\022\014\n\004Succ\030\001 \002(\005\022\r\n\005MemID\030\002 \002(\005\022\017\n\007SvrTim" +
      "e\030\004 \002(\005\022\024\n\014IsSelectCamp\030\005 \002(\005\022\020\n\010LoginSe" +
      "q\030\006 \002(\r\022\022\n\nRegTaskDay\030\007 \002(\005*F\n\010MSG_TYPE\022" +
      "\r\n\tLOGIN_REQ\020\005\022\r\n\tLOGIN_RES\020\006\022\r\n\tHEART_R" +
      "EQ\020\t\022\r\n\tHEART_RES\020\nB\rB\013RichManBean"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CsHeartReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CsHeartReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CsHeartReq_descriptor,
              new java.lang.String[] { "SvrTime", });
          internal_static_CsHeartRes_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CsHeartRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CsHeartRes_descriptor,
              new java.lang.String[] { "SvrTime", "MessageCount", });
          internal_static_LoginReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_LoginReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoginReq_descriptor,
              new java.lang.String[] { "Uin", "AccName", "Enc", });
          internal_static_LoginRes_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_LoginRes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoginRes_descriptor,
              new java.lang.String[] { "Succ", "MemID", "SvrTime", "IsSelectCamp", "LoginSeq", "RegTaskDay", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
